#你的GitHub username 
owner: auteen

#你的GitHub repo name 
repo: autoreplit

#加入要监控的网站名称与URL ,可以添加多个网站
sites: 
  - name: repl.co
    url: https://hello-repl.auteen.repl.co
  - name: replTrojan
    url: https://replit-trojan.auteen.repl.co
  - name: vlessray
    url: https://vlessray.auteen.repl.co
  - name: doprax
    url: https://dop.nile.vip/

status-website: 
    #cname: demo.upptime.js.org (移除) 
    baseUrl: /upptime
    
#自定义状态页面的navbar名称与链接
navbar: 
    - title: upptime
      href: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
