#你的GitHub username 
owner: auteen

#你的GitHub repo name 
repo: upptime

#加入要监控的网站名称与URL ,可以添加多个网站
sites: 
  - name: repl.co
    url: https://hello-repl.auteen.repl.co


#有域名的按照以下模版填写
status-website: 
    cname: repl.co
    
#自定义状态页面的navbar名称与链接
navbar: 
    - title: upptime
      href: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
